In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [3]:
df=pd.read_csv('D:\\py\\ML\\4_save_model\\homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [5]:
reg.predict([[3300]])

C:\Users\sriva\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [6]:
reg.coef_

array([135.78767123])

In [7]:
reg.intercept_

180616.43835616432

In [8]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(reg,file)

In [14]:
with open('model_pickle','rb') as file:
    ss=pickle.load(file)


In [15]:
ss.predict([[3300]])

C:\Users\sriva\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [16]:
ss.coef_

array([135.78767123])

In [17]:
 import num2words