In [1]:
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
l1 = [1, 4, 5, 2, 6, 3]
# l1 = [1, 1235234, 45 , 5, 10 ,125]
# l1 = [[2, 5, 3], [4, 1, 6]]

In [4]:
arr = np.array(l1, dtype = 'int16')
arr

array([1, 4, 5, 2, 6, 3], dtype=int16)

In [5]:
zeros_arr = np.zeros((2, 4), dtype = 'int')
ones_arr = np.ones((2, 4), dtype = 'int')
range_arr = np.arange(5, 15)
lin_arr = np.linspace(2, 10, 5)
identity_arr = np.identity(5)
empty_arr = np.empty((2,4), dtype = np.int16)

In [6]:
lin_arr

array([ 2.,  4.,  6.,  8., 10.])

In [7]:
print(arr.shape, arr.dtype, arr.ndim, arr.size, arr.nbytes)
print(arr.argmax(), arr.argmin())

(6,) int16 1 6 12
4 0


In [8]:
new_arr = np.where(arr > 4, 100, arr)
new_arr

array([  1,   4, 100,   2, 100,   3], dtype=int16)

In [9]:
new_arr = new_arr * 2
new_arr

array([  2,   8, 200,   4, 200,   6], dtype=int16)

In [10]:
new_arr = new_arr.reshape(2, 3)
new_arr

array([[  2,   8, 200],
       [  4, 200,   6]], dtype=int16)

In [11]:
new_arr.reshape(6)

array([  2,   8, 200,   4, 200,   6], dtype=int16)